- name: Eric Dill
  email: edill@bnl.gov
  alternate_emails:
  - ericdill@users.noreply.github.com
  - edill@anaconda.com
  - eric.dill@maxpoint.com
  - thedizzle@gmail.com
  aliases:
  - ericdill
  num_commits: 118
  first_commit: 2015-10-02 08:42:27
- name: Filipe Fernandes
  aliases:
  - Filipe
  email: ocefpaf@gmail.com
  alternate_emails:
  - ocefpaf@gmail.com
  num_commits: 18
  first_commit: 2018-10-19 09:20:59
  github: ocefpaf
- name: Christopher J. Wright
  email: cjwright4242@gmail.com
  num_commits: 6
  first_commit: 2019-07-06 13:51:23
- name: Tony Fast
  email: tony.fast@gmail.com
  num_commits: 1
  first_commit: 2018-09-12 18:02:38
