language: python
sudo: false

python:
- 2.7
- 3.4
- 3.5

install:
  - pip install -r requirements.txt
  - pip install pytest coverage codecov
  - python setup.py install

script:
  - coverage run -m pytest -vrsx

after_success:
  - codecov
