language: python
sudo: false

python:
- 2.7
- 3.4
- 3.5

install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - pip install pytest coverage codecov
  - python setup.py install
  # Need to clean up the git repository or pytest gets confused by the extra
  # cruft that python setup.py install leaves behind
  - git clean -xfd

script:
  - coverage run -m pytest -vrsx
  - coverage report -m

after_success:
  - codecov
