language: python
sudo: false

matrix:
  include:
    - python: 2.7
    - python: 3.3
    - python: 3.4
    - python: 3.5

before_install:
  # - wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh -O miniconda.sh
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda config --add channels ericdill
  - conda config --set always_yes true
  - conda create -n testenv python=$TRAVIS_PYTHON_VERSION pytest stdlib-list
  - source activate testenv
  - echo $TRAVIS_PYTHON_VERSION
  - if [ $TRAVIS_PYTHON_VERSION == "33" ]; then
      pip install nbformat;
    else
      conda install nbformat;
    fi;
  - pip install codecov pytest-cov coveralls
  - python setup.py install

script:
  - ./test

after_success:
  - codecov
  - coveralls
