language: python
sudo: false

matrix:
  include:
    - python: 2.6
    - python: 2.7
    - python: 3.3
    - python: 3.4
    - python: 3.5
    - python: nightly
  allow_failures:
    - python: nightly
    - python: 2.6

install:
  - pip install pytest codecov pytest-cov
  - python setup.py install

script:
  - ./test

after_success:
  - codecov
